allowBuilds:
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
ignoredBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
overrides:
  kysely: 0.27.4
